exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'make_thumbs.sh']

markdown: redcarpet

redcarpet:
    extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "with_toc_data", "fenced_code_blocks"]
